export const EUROLEAGUE_TEAMS = [
  { id: "efe", name: "Αναντολού Εφές", abbr: "EFE" },
  { id: "asv", name: "Αρμάνι Μιλάνο", abbr: "ASV" },
  { id: "vil", name: "Βιλερμπάν", abbr: "VIL" },
  { id: "val", name: "Βαλένθια", abbr: "VAL" },
  { id: "vir", name: "Βίρτους Μπολόνια", abbr: "VIR" },
  { id: "beo", name: "Ερυθρός Αστέρας", abbr: "BEO" },
  { id: "zal", name: "Ζαλγκίρις", abbr: "ZAL" },
  { id: "mac", name: "Μακάμπι Τελ Αβίβ", abbr: "MAC" },
  { id: "bas", name: "Μπασκόνια", abbr: "BAS" },
  { id: "bay", name: "Μπάγερν Μονάχου", abbr: "BAY" },
  { id: "bar", name: "Μπαρτσελόνα", abbr: "BAR" },
  { id: "mco", name: "Μονακό", abbr: "MCO" },
  { id: "dub", name: "Ντουμπάι Μπάσκετ", abbr: "DUB" },
  { id: "oly", name: "Ολυμπιακός", abbr: "OLY" },
  { id: "pan", name: "Παναθηναϊκός", abbr: "PAN" },
  { id: "par", name: "Παρί Μπάσκετ", abbr: "PAR" },
  { id: "prt", name: "Παρτιζάν", abbr: "PRT" },
  { id: "rma", name: "Ρεάλ Μαδρίτης", abbr: "RMA" },
  { id: "fen", name: "Φενερμπαχτσέ", abbr: "FEN" },
  { id: "hap", name: "Χαποέλ Τελ Αβίβ", abbr: "HAP" },
];